# Run Continuous Integration on every push
# This tests Python 3.8
name: python_compatibility_3.8
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Python 3.8 eggs
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.eggs
        key: python-compatibility-3.8-eggs

    - name: Run tests on 3.8 latest
      run: docker run -v "${GITHUB_WORKSPACE}:/home/ymmsl-python" python:3.8 /bin/bash -c 'cd /home/ymmsl-python && pip install -U pip setuptools wheel && python setup.py test'
